title: website test
description: description of the website
theme: just-the-docs

url: https://lmangall.github.io/site

aux_links:
  Template Repository: https://github.com/lmangall/lmangall.github.io.git

logo: "/assets/images/logo.png"
